# Generated by Django 4.0.4 on 2022-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
